[build]
  command = "prisma generate && next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dtybwto2n"
  NODE_VERSION = "18"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@prisma/client"]
  included_files = ["prisma/**"]

[dev]
  command = "npm run dev"
  targetPort = 3000

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true 