[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = ""
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@prisma/client"]
  included_files = ["prisma/**"]

[dev]
  command = "npm run dev"
  targetPort = 3000 